version: "3"
services:
  postgres:
    container_name: projects-postgres
    image: library/postgres:13
    ports:
    - 5433:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
    - /Users/michaelbarclaypersonal/Development/postgres:/var/lib/postgresql/data

