resources:
  - name: ((project-name))-repo
    type: git
    icon: github
    source:
      uri: ssh://git@10.5.10.11:222/mbarclay36/projects-api.git
      branch: master
      private_key: ((private-key))
      private_key_passphrase: ((private-key-passphrase))
  - name: ((project-name))-image
    type: docker-image
    icon: docker
    source:
      repository: docker-registry.bigmike.dev/((project-name))

jobs:
  - name: build-push-deploy
    plan:
      - get: ((project-name))-repo
        trigger: true
        version: latest
      - task: run-tests
        config:
          platform: linux
          params:
            DB_CONNECTION: pgsql
            DB_HOST: 10.5.10.11
            DB_PORT: 5432
            DB_DATABASE: projects-testing
            DB_USERNAME: mbarclay36
            DB_PASSWORD: ((pgsql-password))
            JWT_SECRET: ((jwt-secret))
          inputs:
            - name: ((project-name))-repo
          image_resource:
            type: docker-image
            source:
              repository: webdevops/php-nginx
              tag: 8.1
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd ((project-name))-repo
                /usr/local/bin/composer install
                /usr/local/bin/php artisan test
      - put: ((project-name))-image
        params:
          build: ((project-name))-repo
          dockerfile: ((project-name))-repo/docker/Dockerfile
          tag_file: ((project-name))-repo/.git/ref
          tag_as_latest: true
      - task: run-portainer-webhook
        config:
          platform: linux
          privileged: true
          image_resource:
            type: docker-image
            source:
              repository: concourse/oci-build-task
          run:
            path: /bin/sh
            args:
              - -c
              - |
                apk add curl && apk add --upgrade curl
                curl --location --request POST 'http://10.5.10.11:9000/api/stacks/webhooks/e22679a0-188c-466a-bbd9-7796f0d685fc'
    on_success:
      task: job-success
      config:
        platform: linux
        privileged: true
        image_resource:
          type: docker-image
          source:
            repository: concourse/oci-build-task
        run:
          path: /bin/sh
          args:
            - -c
            - |
              apk add curl && apk add --upgrade curl
              curl --location --request POST 'https://gotify.bigmike.dev/message?token=AfI_HNqzh6EXFk0' --header 'Content-Type: application/json' \
              --data-raw '{"message": "project-api pipeline success","priority": 10,"title": "Concourse Success"}'
    on_failure:
      task: job-failure
      config:
        platform: linux
        privileged: true
        image_resource:
          type: docker-image
          source:
            repository: concourse/oci-build-task
        run:
          path: /bin/sh
          args:
            - -c
            - |
              apk add curl && apk add --upgrade curl
              curl --location --request POST 'https://gotify.bigmike.dev/message?token=AfI_HNqzh6EXFk0' --header 'Content-Type: application/json' \
              --data-raw '{"message": "project-api pipeline failed","priority": 10,"title": "Concourse Failure"}'


